services:
  rust-app:
    image: rust:latest
    container_name: rust-app-container
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - TZ=Europe/Moscow
      - MATRICES_COUNT=10000
    command: cargo run
    restart: unless-stopped
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '7'
